IntermediarioMVC/Models/Provider.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IntermediarioMVC.Models
{
    public class Provider : Person
    { 
        #region Properties

        [Key]
        public int ProviderId { get; set; }

        #endregion

        #region Navigation properties

        public virtual ICollection<Purchase> Purchases { get; set;}

        #endregion

    }
}

IntermediarioMVC/Models/ProviderView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace IntermediarioMVC.Models
{
    [NotMapped]
    public class ProviderView : Provider
    {
        [Display(Name = "Image")]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}

IntermediarioMVC/Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IntermediarioMVC.Models;
using IntermediarioMVC.Helpers;

namespace IntermediarioMVC.Controllers
{
    public class ProvidersController : Controller
    {
        private IntermediarioMVCContext db = new IntermediarioMVCContext();

        // GET: Providers
        public ActionResult Index()
        {
           
            return View(db.Providers.ToList());
        }

        // GET: Providers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Provider provider = db.Providers.Find(id);
            if (provider == null)
            {
                return HttpNotFound();
            }
            return View(provider);
        }

        // GET: Providers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Providers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProviderView providerView)
        {
            if (ModelState.IsValid)
            {
                var pic = string.Empty;
                var folder = "~/Content/Images";
                if (providerView.ImageFile != null)
                {
                    pic = FileHelper.UploadPhoto(providerView.ImageFile, folder);
                    pic = string.Format("{0}/{1}", folder, pic);
                }
                Provider provider = ToProvider(providerView);
                provider.ImagePath = pic;
                db.Providers.Add(provider);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(providerView);
        }

        // GET: Providers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Provider provider = db.Providers.Find(id);
            if (provider == null)
            {
                return HttpNotFound();
            }
            ProviderView providerView = ToView(provider);

            return View(providerView);
        }

        private ProviderView ToView(Provider provider)
        {
            return new ProviderView()
            {
                Address = provider.Address,
                FirstName = provider.FirstName,
                ImagePath = provider.ImagePath == null ? "~/Content/Images/noImage.png" : provider.ImagePath,
                LastName = provider.LastName,
                PhoneNumber = provider.PhoneNumber,
                ProviderId = provider.ProviderId,
                Purchases = provider.Purchases,
            };
        }

        // POST: Providers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProviderView providerView)
        {
            if (ModelState.IsValid)
            {
                var pic = providerView.ImagePath;
                var folder = "~/Content/Images";
                if (providerView.ImageFile != null)
                {
                    pic = FileHelper.UploadPhoto(providerView.ImageFile, folder);
                    pic = string.Format("{0}/{1}", folder, pic);
                }
                Provider provider = ToProvider(providerView);
                provider.ImagePath = pic;
                db.Entry(provider).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(providerView);
        }

        private Provider ToProvider(ProviderView providerView)
        {
            return new Provider()
            {

                Address = providerView.Address,
                FirstName = providerView.FirstName,
                ImagePath = providerView.ImagePath,
                PhoneNumber = providerView.PhoneNumber,
                LastName = providerView.LastName,
                ProviderId = providerView.ProviderId,
                Purchases = providerView.Purchases

            };
        }

        // GET: Providers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Provider provider = db.Providers.Find(id);
            if (provider == null)
            {
                return HttpNotFound();
            }
            return View(provider);
        }

        // POST: Providers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Provider provider = db.Providers.Find(id);
            db.Providers.Remove(provider);
            try
            {
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                if (ex.InnerException != null &&
                    ex.InnerException.InnerException != null &&
                    ex.InnerException.InnerException.Message.Contains("REFERENCE"))
                {
                    ViewBag.Error = "The provider can not be deleted because it has related records";
                }
                else
                {
                    ViewBag.Error = ex.Message;
                }
                return View(provider);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IntermediarioMVC/Views/Providers/Create.cshtml
@model IntermediarioMVC.Models.ProviderView

@{
    ViewBag.Title = "Create";
}

<h2>Create provider</h2>


@using (Html.BeginForm("Create", "Providers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-light btn-file">
                    @Html.TextBoxFor(modelo => modelo.ImageFile, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, new { @class="btn btn-light"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IntermediarioMVC/Views/Providers/Delete.cshtml
@model IntermediarioMVC.Models.Provider

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Provider</h4>
    <h4 class="alert-danger">@ViewBag.Error</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IntermediarioMVC/Views/Providers/Details.cshtml
@model IntermediarioMVC.Models.Provider

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Provider</h4>
    <hr />
    <div class="row">
        <div class="col-md-7">

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FirstName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LastName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PhoneNumber)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Address)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Address)
                </dd>

             
            </dl>

        </div>
        <div class="col-md-5">
            <img src="@Url.Content(Model.ImagePath)" alt="Image" style="width:400px;height:400px;max-width: 100%; height: auto;" />

        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProviderId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IntermediarioMVC/Views/Providers/Edit.cshtml
@model IntermediarioMVC.Models.ProviderView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Provider</h2>


@using (Html.BeginForm("Edit", "Providers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Provider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProviderId)
        @Html.HiddenFor(model => model.ImagePath)


        <div class="row">
            <div class="col-md-7">
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <span class="btn btn-default btn-file">
                            @Html.TextBoxFor(modelo => modelo.ImageFile, new { type = "file" })
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <img src="@Url.Content(Model.ImagePath)" alt="Image" style="width:400px;height:400px;max-width: 100%; height: auto;" />

            </div>
        </div>

       
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IntermediarioMVC/Views/Providers/Index.cshtml
@model IEnumerable<IntermediarioMVC.Models.Provider>

@{
    ViewBag.Title = "Index";
}

<h2>Providers</h2>

<p>
    @Html.ActionLink("New Provider", "Create", new { }, new { @class="btn btn-primary"})
</p>
<table class="table table-striped table-bordered">
    <tr>
        <th>
            Image
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @if (!string.IsNullOrEmpty(item.ImagePath))
            {
             <img src="@Url.Content(item.ImagePath)" alt="Image" class="mr-0 mt-0 rounded-circle" style="width:60px;height:60px;max-width: 100%; height: auto;" />
            }

        </td>

        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ProviderId }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Details", "Details", new { id = item.ProviderId }, new { @class = "btn btn-info" })
            @Html.ActionLink("Delete", "Delete", new { id = item.ProviderId }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>