IntermediarioMVC/Models/Purchase.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IntermediarioMVC.Models
{
    public class Purchase
    {
        #region Properties

        [Key]
        public int PurchaseId { get; set; }

        [Required(ErrorMessage = "The field {0} is required")]
        
        public int ProviderId { get; set; }

        [Required(ErrorMessage = "The field {0} is required")]
        [Display(Name = "Product")]
        public int ProductId { get; set; }

        [Display(Name = "Price input")]
        [DataType(DataType.Currency)]
        [Required(ErrorMessage = "The field {0} is required")]
        public double PriceInput { get; set; }

        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "The field {0} is required")]
        public DateTime DatePurchase { get; set; }

        [Required(ErrorMessage = "The field {0} is required")]
        [Display(Name = "Amount")]
        public double Amount { get; set; }
        public string Remarks { get; set; }

        #endregion

        #region Navigation properties

        public virtual Provider Provider { get; set; }

        public virtual Product Product { get; set; }
        #endregion

    }
}

IntermediarioMVC/Models/Sale.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IntermediarioMVC.Models
{
    public class Sale
    {
        #region Properties

        [Key]
        public int SaleId { get; set; }
        public int? PayId { get; set; }
        public int ProductInStockId { get; set; }
        public int? CustomerId { get; set; }
        public int? MessengerId { get; set; }

        [Display(Name = "Date of Sale")]
        [DataType(DataType.Date)]
        public DateTime DateOfSale { get; set; }
        public double Amount { get; set; }

        [Display(Name = "Price of sale")]
        [DataType(DataType.Currency)]
        public double SalePrice { get; set; }

        [Display(Name = "State of sale")]
        public SaleState SaleState { get; set; }
        #endregion

        #region Navigation properties
        public virtual Pay Pay { get; set; }
        public virtual ProductInStock ProductInStock { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Messenger Messenger { get; set; }

        #endregion

    }

    public enum SaleState
    {
        PendingLiquidate, Liquidated, Certificated
    }
}

IntermediarioMVC/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IntermediarioMVC.Models;

namespace IntermediarioMVC.Controllers
{
    public class TransferController : Controller
    {
        private IntermediarioMVCContext db = new IntermediarioMVCContext();


        #region Purchase operations

        
        public ActionResult Purchase(string productName)
        {
            var purchases = db.Purchases.Include(pu => pu.Provider)
                                        .Include(pu => pu.Product)
                                        .ToList();
            if (string.IsNullOrEmpty(productName))
            {
                return View(purchases);
            }

            return View(
                
                purchases.Where(p => p.Product.ProductName
                                              .ToLower()
                                              .Equals(productName.ToLower()))
                                              .ToList()
                );

        }

        public ActionResult NewPurchase()
        {
            ViewBag.ProviderId = new SelectList(db.Providers, "ProviderId", "FirstName");
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "ProductName");

            return View();
        }

        [HttpPost]
        public ActionResult NewPurchase(Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                

                using (var transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        //Add purchase to list of purchases
                        db.Purchases.Add(purchase);
                        db.SaveChanges();

                        //Add amount in stock table 

                        var productInStock = db.ProductInStocks
                                                    .Where(ps => ps.ProductId == purchase.ProductId &&
                                                                 ps.ProviderId == purchase.ProviderId &&
                                                                 ps.State == StateEnum.Available)
                                                    .FirstOrDefault();

                        if(productInStock == null)
                        {
                            productInStock = new ProductInStock()
                            {
                                Amount = purchase.Amount,
                                PriceInput = purchase.PriceInput,
                                ProductId = purchase.ProductId,
                                ProviderId = purchase.ProviderId,
                                State = StateEnum.Available
                            };
                            var code = GenerateCode(productInStock);
                            productInStock.Code = code;
                            db.ProductInStocks.Add(productInStock);
                        }
                        else
                        {
                            productInStock.Amount += purchase.Amount;
                            db.Entry(productInStock).State = EntityState.Modified;
                        }
                        
                        db.SaveChanges();
                        transaction.Commit();
                    }
                    catch (Exception)
                    {

                        transaction.Rollback();
                        ModelState.AddModelError(
                            string.Empty,
                            "Purchase can not be added, Database thrown an error"
                            );
                        return View(purchase);
                    }
                }

                return RedirectToAction("Purchase");
            }

            ViewBag.ProviderId = new SelectList(db.Providers, "PersonId", "FirstName",purchase.ProviderId);
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "ProductName", purchase.ProductId);
            return View(purchase);
        }

        public string GenerateCode(ProductInStock productInStock)
        {
            var code = productInStock.ProductId.ToString() +
                       productInStock.ProviderId.ToString() +
                       productInStock.State.ToString();
            return code;
        }

        #endregion

        #region Stock action result
        public ActionResult Stock()
        {
            ViewBag.Alert = "";
            var productInStockList = db.ProductInStocks.Include(s => s.Provider)
                                                       .Include(s => s.Product);
                                                       
            return View(productInStockList.Where(ps => ps.Amount > 0).ToList());
        }
        #endregion

        #region Change state of product in stock

        public ActionResult ModifyState(int productInStockId)
        {
            var productInStock = db.ProductInStocks.Find(productInStockId);
            var changeState = new ChangeState()
            {
                BeforeState = productInStock.State,
                Date = DateTime.Now,
                ProductInStockId = productInStock.ProductInStockId,
                ProductInStock = productInStock,

            };


            return View(changeState);
        }

        [HttpPost]
        public ActionResult ModifyState(ChangeState changeState)
        {
            if (ModelState.IsValid)
            {

                if (changeState.BeforeState == changeState.NextState)
                {
                    ModelState.AddModelError(
                        string.Empty,
                        "Before and Next state can not be same values"
                        );
                    return View(changeState);
                }

                if (changeState.Amount == 0)
                {
                    ModelState.AddModelError(
                        string.Empty,
                        "Amount can not be equals  0");
                    return View(changeState);
                }

                var productInStock = db.ProductInStocks.Find(changeState.ProductInStockId);

                if (changeState.Amount > productInStock.Amount)
                {
                    ModelState.AddModelError(
                        string.Empty,
                        string.Format("Amount exceed permissible value: {0}", productInStock.Amount)
                        );
                    return View(changeState);
                }



                using (var transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        //Add changeState to list ChangeStates in database

                        db.ChangeStates.Add(changeState);
                        db.SaveChanges();

                        //substract amount of changeState in productInStock where property State has BeforeState  

                        productInStock.Amount -= changeState.Amount;
                        db.Entry(productInStock).State = EntityState.Modified;
                        db.SaveChanges();

                        //Add amount of changeState in productInStock where property State has NextState 

                        var code = GenerateCode(

                            new ProductInStock()
                            {
                                ProductId = changeState.ProductInStock.ProductId,
                                ProviderId = changeState.ProductInStock.ProviderId,
                                State = changeState.NextState
                            });

                        var productInStockNextState = db.ProductInStocks.Where(p => p.Code.Equals(code))
                                                                        .FirstOrDefault();

                        if (productInStockNextState == null)
                        {
                            productInStockNextState = new ProductInStock()
                            {
                                Amount = changeState.Amount,
                                Code = code,
                                PriceInput = productInStock.PriceInput,
                                ProductId = productInStock.ProductId,
                                ProviderId = productInStock.ProviderId,
                                State = changeState.NextState
                            };
                            db.ProductInStocks.Add(productInStockNextState);
                        }
                        else
                        {
                            productInStockNextState.Amount += changeState.Amount;
                            db.Entry(productInStockNextState).State = EntityState.Modified;
                        }

                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Stock");
                    }
                    catch (Exception)
                    {

                        transaction.Rollback();
                        ModelState.AddModelError(
                            string.Empty,
                            "Purchase can not be added, Database thrown an error"
                            );
                        return View(changeState);
                    }
                }

            }

            return View(changeState);
        }

        #endregion
        
        #region Sale operations

        //New sale method
        public ActionResult SaleAction(int productInStockId)
        {
            var productInStock = db.ProductInStocks.Find(productInStockId);
            var sale = new Sale()
            {
                DateOfSale = DateTime.Now,
                ProductInStockId = productInStock.ProductInStockId,

IntermediarioMVC/Views/Transfer/ModifyState.cshtml
@model IntermediarioMVC.Models.ChangeState
@{
    ViewBag.Title = "ModifyState";
}

<h2>ModifyState</h2>
@Html.ValidationSummary(true, "", new { @class = "text-danger" })

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
     
        @Html.HiddenFor(model => model.ProductInStockId)
        @Html.HiddenFor(model => model.Date)
        @Html.HiddenFor(model => model.BeforeState)
     
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ProductInStock.Product.ProductName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProductInStock.Product.ProductName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ProductInStock.Provider.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProductInStock.Provider.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BeforeState)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BeforeState)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
        </dl>
        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NextState, "Next State", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.NextState, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NextState, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Modify State" class="btn btn-success" />
            </div>
        </div>
        
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Stock","Transfer", new { }, new { @class = "btn btn-light"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IntermediarioMVC/Views/Transfer/NewPurchase.cshtml
@model IntermediarioMVC.Models.Purchase

@{
    ViewBag.Title = "NewPurchase";
}

<h2>New purchase</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Purchase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderId, "Provider", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProviderId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProviderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, "Product", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceInput, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceInput, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceInput, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatePurchase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatePurchase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatePurchase, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Purchase","Transfer", new { }, new { @class="btn btn-light"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IntermediarioMVC/Views/Transfer/Purchase.cshtml
@model IEnumerable<IntermediarioMVC.Models.Purchase>

@{
    ViewBag.Title = "Purchase";
}

<h2>Purchases</h2>
<hr/>
<p>
    @Html.ActionLink("New Purchase", "NewPurchase","Transfer",new { }, new { @class="btn btn-primary"})
</p>

@using (Html.BeginForm("Purchase", "Transfer", FormMethod.Get))
{
    <ul class="list-inline">
        <li class="list-inline-item">
            <p>Find by product:</p>
        </li>
        <li class="list-inline-item">
            @Html.TextBox("productName", new { }, new { @class = "form-control" })
            
        </li>
        <li class="list-inline-item">
            <input type="submit" value="Filter" class="btn btn-success" />
        </li>
    </ul>

}

<table class="table table-info table-striped">
    <tr>
        <th>
            Provider
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PriceInput)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatePurchase)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Remarks)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Provider.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceInput)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePurchase)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Remarks)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { purchaseId = item.PurchaseId }, new { @class = "btn btn-info" })
           </td>
        </tr>
    }

</table>

IntermediarioMVC/Views/Transfer/Sale.cshtml
@{
    ViewBag.Title = "Sale";
}

<h2>Sale</h2>

IntermediarioMVC/Views/Transfer/SaleAction.cshtml
@model IntermediarioMVC.Models.Sale
@{
    ViewBag.Title = "Sale";
}

<h2>New Sale</h2>
<hr/>
@Html.ValidationSummary(true, "", new { @class = "text-danger" })

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.HiddenFor(model => model.ProductInStockId)
       
        <div class="row my-3">
            <div class="col-sm-12">
                <ul class="list-inline text-info">
                    <li class="list-inline-item"><img src="@Url.Content(Model.ProductInStock.Provider.ImagePath)"
                             alt="Image" class="ml-5 mt-0 rounded-circle"
                             style="width:60px;height:60px;max-width: 100%; height: auto;" />
                    </li>
                    <li class="list-inline-item"><h4 class="ml-0">@Model.ProductInStock.Provider.FullName </h4></li>
                </ul>
                
            </div>
         

        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    @Html.LabelFor(model => model.DateOfSale, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateOfSale, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DateOfSale, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SalePrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SalePrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SalePrice, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SaleState, "State of sale", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.SaleState, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SaleState, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="To sell" class="btn btn-success" />
                    </div>
                </div>

            </div>
            <div class="col-md-4 ml-0">
                <img src="@Url.Content(Model.ProductInStock.Product.ImagePath)" class="img-fluid img-thumbnail" width="400" height="400"/>
            </div>
        </div>
       
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Stock", "Transfer", new { }, new { @class = "btn btn-light" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IntermediarioMVC/Views/Transfer/Stock.cshtml
@model IEnumerable<IntermediarioMVC.Models.ProductInStock>

@{
    ViewBag.Title = "Stock";
}

<h2>Stock</h2>
<hr/>
<h4 class="alert-danger">@ViewBag.Alert</h4>
<table class="table table-info table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Provider.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.PriceInput)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th></th>
        <th></th>
      
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Provider.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product.ProductName)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.PriceInput)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.ActionLink("Modify State", "ModifyState", new { productInStockId = item.ProductInStockId }, new { @class = "btn btn-warning" })
               
            </td>
            
            <td>
                @if (item.State == IntermediarioMVC.Models.StateEnum.Available)
                {
                    @Html.ActionLink("To sell", "SaleAction", new { productInStockId = item.ProductInStockId }, new { @class = "btn btn-success" })
                }
            </td>
           
        </tr>
    }

</table>